services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_DATABASE=neo4j
      - PORT=3001
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    restart: unless-stopped